--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/EasyForms
build-by-default: true
branches:
- master
projects:
  libEasyUI:
    path: ""
    model: virion
    type: library
...
